web:
  image: nginx:latest
  ports: 
    - "80:80"
  volumes:
    - ..:/code
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./vhost.conf:/etc/nginx/conf.d/vhost.conf
  links:
    - php

php:
  image: php:7-fpm
  volumes:
    - ..:/code
